"use client";
import {useEffect,useRef,useState} from "react";
type Doc={id:string;title:string;project:string;source_type:string;document_type:string;authoritative_level:number;updated_at:string|null;url:string;owner:string;relationships:{target:string;type:string}[]};
type Corpus={documents:Doc[];chunks:number;built_at:string;hash:string;stats:{rows:number;tests:number;runs:number;period_start:string;period_end:string};profiles:Record<string,{type:string;strategy:string;basis:string}>;model_configured:boolean;embedding:{model:string;dimensions:number};chunking:{words:number;overlap:number}};
type Evidence=Doc&{content:string;citation:number;chunk_id:string;freshness:{state:string;days:number|null};graph_hop:{via:string;type:string}|null;source_rows?:number[]};
type Result={status:string;reason:string;project:string;evidence:Evidence[];claims:{text:string;citation:number;chunk_id:string}[];confidence:{score:number|null;kind:string};latency_ms:number;generation:string;model_status:string;unavailable:string[];conflicts?:{key:string;sources:string[];values:string[];preferred:string}[];mentor:{strategy:string;sections:string[];exercise:string;knowledge_check:string}|null};
type Report={generated_at:string;methodology:string;metrics:Record<string,number|null>;corpus:{graph_nodes:number;graph_edges:number};cases:{question:string;expected_status:string;actual_status:string;status_correct:boolean;recall:number|null}[];graphQueries:{question:string;vector:{recall:number};graph:{recall:number}}[]};
const percent=(n:number|null|undefined)=>n==null?"Not measured":(100*n).toFixed(1)+"%";
const date=(s:string|null)=>s?new Date(s).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}):"Update date unknown";
const starter=["What are the BSP Services sample portfolio results?","Which tests executed in RUN-00001?","What are the ACs for KAT-1499?","How do Confluence inherited view restrictions work?"];
const sources=["jira","confluence","sharepoint","bitbucket","slack","katalon","testops"];
export default function Workspace(){
 const [corpus,setCorpus]=useState<Corpus|null>(null),[report,setReport]=useState<Report|null>(null),[question,setQuestion]=useState(starter[0]),[project,setProject]=useState("All"),[mode,setMode]=useState("ask"),[strategy,setStrategy]=useState("graph"),[tab,setTab]=useState("ask"),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[filter,setFilter]=useState(""),[seed,setSeed]=useState("RUN-00001");
 const active=useRef<AbortController|null>(null);
 async function ask(q=question,p=project,m=mode,s=strategy){
  active.current?.abort();const ctl=new AbortController();active.current=ctl;setBusy(true);setError("");setQuestion(q);setProject(p);setMode(m);setTab("ask");
  try{const response=await fetch("/api/ask",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q,project:p,mode:m,strategy:s}),signal:ctl.signal});const value=await response.json();if(!response.ok)throw new Error(value.error||"Unable to retrieve evidence");setResult(value);return value}
  catch(e){if(!ctl.signal.aborted)setError(e instanceof Error?e.message:"Request failed")}
  finally{if(active.current===ctl)setBusy(false)}
 }
 useEffect(()=>{const ctl=new AbortController();Promise.all([fetch("/api/corpus",{signal:ctl.signal}).then(r=>{if(!r.ok)throw new Error("Corpus unavailable");return r.json()}),fetch("/api/evaluation",{signal:ctl.signal}).then(r=>r.ok?r.json():null)]).then(([c,r])=>{setCorpus(c);setReport(r)}).catch(e=>{if(!ctl.signal.aborted)setError(e.message)});return()=>ctl.abort()},[]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{context.registerTool({name:"ask_qe",title:"Ask QE",description:"Retrieve authorized QE evidence and update the visible answer.",inputSchema:{type:"object",properties:{question:{type:"string"},project:{type:"string"}},required:["question"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const x=input as {question:string;project?:string};if(typeof x.question!=="string"||x.question.length<3||x.question.length>2000)throw new Error("Invalid question");const r=await ask(x.question,x.project||"All");if(!r)throw new Error("Retrieval failed");return{status:r.status,citations:r.evidence.length}}},{signal:life.signal})}catch{}return()=>life.abort()},[]);
 const docs=corpus?.documents||[],selected=docs.find(d=>d.id===seed),neighbors=selected?.relationships.map(e=>({edge:e,doc:docs.find(d=>d.id===e.target)})).filter(x=>x.doc)||[];
 const visible=docs.filter(d=>(project==="All"||d.project===project||d.project==="GLOBAL")&&[d.id,d.title,d.source_type,d.project].join(" ").toLowerCase().includes(filter.toLowerCase()));
 return <main><nav><a className="wordmark" href="/">QI<span>QEI Knowledge<br/><small>Intelligence / Week 2</small></span></a><div className="topnav">{[["ask","Ask QE"],["corpus","Corpus"],["graph","Evidence graph"],["eval","Evaluation"]].map(([key,label])=><button key={key} aria-current={tab===key?"page":undefined} onClick={()=>setTab(key)}>{label}</button>)}</div><a className="repo" href="https://github.com/lkalyanams29/qei-knowledge-intelligence-week2" target="_blank" rel="noreferrer">Project ↗</a></nav>
 <section className="workspace"><div className="heading"><div><p className="eyebrow">QUALITY ENGINEERING • EVIDENCE WORKSPACE</p><h1>{tab==="ask"?"Answers begin with evidence.":tab==="corpus"?"Know what the corpus knows.":tab==="graph"?"Follow the recorded relationships.":"Measure before you claim."}</h1></div><div className="scope"><label htmlFor="project">Project context</label><select id="project" value={project} onChange={e=>{setProject(e.target.value);setResult(null)}}><option value="All">All projects</option>{Object.keys(corpus?.profiles||{}).map(p=><option key={p}>{p}</option>)}</select></div></div>
 <div className="scopeNote"><span className="dot"/>Supplied sample · {corpus?date(corpus.stats.period_start)+" – "+date(corpus.stats.period_end):"Loading corpus…"}<span className="sourceNote">{corpus?.model_configured?"Model endpoint configured":"Exact-source answers · model endpoint not configured"}</span></div>
 {project!=="All"&&corpus?.profiles[project]&&<p className="profile"><strong>{corpus.profiles[project].type}</strong> · {corpus.profiles[project].strategy} <span>{corpus.profiles[project].basis}</span></p>}
 {error&&<div className="error" role="alert">{error}</div>}{notice&&<p role="status">{notice}</p>}
 {tab==="ask"&&<><form className="composer" onSubmit={e=>{e.preventDefault();void ask()}}><div className="composerTop"><div className="segmented"><button type="button" aria-pressed={mode==="ask"} onClick={()=>{setMode("ask");setResult(null)}}>Ask QE</button><button type="button" aria-pressed={mode==="mentor"} onClick={()=>{setMode("mentor");setResult(null)}}>Mentor Mode</button></div><label className="retrieval">Retrieval <select value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="graph">Hybrid + graph</option><option value="hybrid">Hybrid</option><option value="vector">Vector baseline</option></select></label></div><label className="srOnly" htmlFor="question">Your QE question</label><textarea id="question" value={question} maxLength={2000} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about a test, run, project strategy or source…"/><div className="composerBottom"><span>Evidence is filtered before it reaches the answer.</span><button disabled={busy||question.trim().length<3} type="submit">{busy?"Retrieving evidence…":"Ask QE →"}</button></div></form>
 <div className="suggestions">{starter.map(q=><button key={q} disabled={busy} onClick={()=>void ask(q,"All")}>{q} ↗</button>)}</div>
 {!result&&!busy&&<div className="empty panel"><h2>Start with a question the sources can answer.</h2><p>The supplied CSV contains {corpus?.stats.tests||"…"} test IDs and {corpus?.stats.runs||"…"} runs. Public tool documentation and the project design notes add context. Jira requirements, code, and enterprise messages have not been imported.</p><div className="quickStats"><span><b>{docs.length||"…"}</b>source records</span><span><b>{corpus?.chunks||"…"}</b>indexed chunks</span><span><b>{report?.corpus.graph_edges||"…"}</b>recorded links</span></div></div>}
 {busy&&<div className="panel" role="status">Searching the authorized snapshot and validating evidence…</div>}
 {result&&!busy&&<div className="answerGrid"><article className="panel answer"><div className="answerMeta"><strong className={"statusTag "+result.status.toLowerCase()}>{result.status.replaceAll("_"," ")}</strong><span>{result.latency_ms.toFixed(0)} ms server</span></div><h2>{result.reason}</h2><div className="quality"><span>Evidence quality <b>{result.confidence.score??"—"}{result.confidence.score!=null?"/100":""}</b></span><small>{result.confidence.kind}</small></div>{result.claims.length?<ol className="claims">{result.claims.map((c,i)=><li key={i}>{c.text} <a className="citation" href={"#evidence-"+c.citation}>[{c.citation}]</a></li>)}</ol>:<p>No supported answer is available for this question. The evidence panel shows any dated context retained for review.</p>}
 {!!result.conflicts?.length&&<div className="error"><b>Conflicting assertions</b>{result.conflicts.map((c,i)=><p key={i}>{c.key}: {c.values.join(" versus ")}. Preferred source by authority/freshness: {c.preferred}. Owner review required.</p>)}</div>}
 {result.mentor&&<section className="mentor"><h3>Learning path · {result.mentor.strategy}</h3><p>The evidence above supports the available parts of this path. Unlinked architecture, implementation and requirement details remain unknown.</p><div>{result.mentor.sections.map((s,i)=><span key={s}>{i+1}. {s}</span>)}</div><h4>Hands-on exercise</h4><p>{result.mentor.exercise}</p><h4>Knowledge check</h4><p>{result.mentor.knowledge_check}</p></section>}
 <p className="generation">{result.model_status}</p><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(result.reason+"\n\n"+result.claims.map(c=>c.text+" ["+c.citation+"]").join("\n")+"\n\n"+result.evidence.map(e=>"["+e.citation+"] "+e.url).join("\n"));setNotice("Answer and source links copied.")}catch{setNotice("Clipboard unavailable in this browser.")}}}>Copy answer + citations</button></article><aside className="panel evidence"><p className="eyebrow">SOURCE PROVENANCE</p><h2>{result.evidence.length} retrieved records</h2>{result.evidence.map(e=><article id={"evidence-"+e.citation} key={e.chunk_id}><div className="evidenceMeta"><b>[{e.citation}] {e.source_type}</b><span>Authority {e.authoritative_level}/5</span></div><h3>{e.title}</h3><p className="sourceId">{e.id} · {e.project}</p><p className="freshness">{e.freshness.state==="stale"?"Dated evidence":e.freshness.state==="unknown"?"Freshness unknown":"Within freshness policy"} · {date(e.updated_at)}</p>{e.graph_hop&&<p className="graphHop">Linked from {e.graph_hop.via} · {e.graph_hop.type}</p>}<details><summary>Read retrieved excerpt</summary><p>{e.content}</p>{e.source_rows&&<small>Derived from CSV rows: {e.source_rows.join(", ")}</small>}</details><a href={e.url} target="_blank" rel="noreferrer">Open original source ↗</a></article>)}{!result.evidence.length&&<p>No accessible evidence was returned.</p>}</aside></div>}</>}
 {tab==="corpus"&&<><div className="sourceTiles">{sources.map(s=>{const count=docs.filter(d=>d.source_type===s).length;return <article key={s}><b>{s}</b><strong>{count}</strong><small>{s==="testops"?"Supplied CSV + public docs":count?"Public documentation only":"No enterprise export"}</small></article>})}</div><section className="panel"><div className="sectionHead"><div><p className="eyebrow">CORPUS MANIFEST</p><h2>{docs.length} records · {corpus?.chunks} chunks</h2></div><input aria-label="Filter corpus" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filter ID, project or source"/></div><p>Indexed {date(corpus?.built_at||null)}. {corpus?.embedding.model}, {corpus?.embedding.dimensions} dimensions. Chunks: up to {corpus?.chunking.words} words with {corpus?.chunking.overlap}-word overlap.</p><div className="tableScroll"><table><thead><tr><th>Source record</th><th>Project</th><th>Type</th><th>Authority</th><th>Source date</th></tr></thead><tbody>{visible.map(d=><tr key={d.id}><td><a href={d.url} target="_blank" rel="noreferrer">{d.id}</a><small>{d.title}</small></td><td>{d.project}</td><td>{d.document_type.replaceAll("_"," ")}</td><td>L{d.authoritative_level}</td><td>{date(d.updated_at)}</td></tr>)}</tbody></table></div></section></>}
 {tab==="graph"&&<section className="panel"><div className="sectionHead"><div><p className="eyebrow">OBSERVED TEST → RUN RELATIONSHIPS</p><h2>{report?.corpus.graph_nodes} nodes · {report?.corpus.graph_edges} directed edges</h2></div><label>Start from a record <select value={seed} onChange={e=>setSeed(e.target.value)}>{docs.filter(d=>d.relationships.length).map(d=><option key={d.id}>{d.id}</option>)}</select></label></div><p>Only relationships recorded in the input are traversed. Requirement, pull request and Step Definition links are absent in the supplied CSV.</p>{selected&&<><div className="seed"><b>{selected.id}</b><span>{selected.title} · {selected.project}</span><button onClick={()=>void ask("History of "+selected.id,selected.project)}>Ask about this record →</button></div><div className="neighbors">{neighbors.map(({edge,doc})=><button key={edge.target} onClick={()=>setSeed(edge.target)}><small>↳ {edge.type.replaceAll("_"," ")}</small><b>{doc?.id}</b><span>{doc?.title}</span></button>)}</div></>}</section>}
 {tab==="eval"&&report&&<section className="panel"><p className="eyebrow">MEASURED DEVELOPMENT EVALUATION</p><h2>25 questions, with evidence of the results</h2><p>{report.methodology}</p><div className="evalCards">{[["Relevant-source recall",percent(report.metrics.relevant_source_recall),"Target ≥90%"],["Correct refusal",percent(report.metrics.correct_refusal),"Target ≥95%"],["Verbatim support",percent(report.metrics.verbatim_support),"Exact quotation check"],["Semantic faithfulness","Not measured","Target ≥95% · human review required"],["Local P95",(report.metrics.p95_local_ms||0).toFixed(1)+" ms","Excludes LLM and network"]].map(([label,value,note])=><article key={label}><span>{label}</span><b>{value}</b><small>{note}</small></article>)}</div><h3>Graph versus vector · 10 relationship questions</h3><p>Linked-test recall at six results: graph <b>{percent(report.metrics.graph_recall)}</b> · vector <b>{percent(report.metrics.vector_recall)}</b>. Larger runs have more related tests than the result limit.</p><div className="comparison">{report.graphQueries.map(q=><div key={q.question}><span>{q.question}</span><div><i style={{width:100*q.graph.recall+"%"}}/><em style={{width:100*q.vector.recall+"%"}}/></div></div>)}</div><p className="legend">Teal: graph · blue: vector. Measured {date(report.generated_at)}.</p><details><summary>Inspect all 25 results</summary><div className="tableScroll"><table><thead><tr><th>Question</th><th>Expected</th><th>Actual</th><th>Recall</th></tr></thead><tbody>{report.cases.map(c=><tr key={c.question+c.expected_status}><td>{c.question}</td><td>{c.expected_status}</td><td>{c.actual_status}</td><td>{percent(c.recall)}</td></tr>)}</tbody></table></div></details><a className="download" href="/api/evaluation" target="_blank" rel="noreferrer">Open complete evaluation JSON ↗</a></section>}
 <footer className="pageFooter">QEI Knowledge Intelligence · Frozen source snapshot · Corpus {corpus?.hash.slice(0,12)||"loading"}</footer></section></main>
}
